version: '3.9'
services:
  cardb:
   container_name: cardb
   image: mcr.microsoft.com/mssql/server:2017-latest
   environment:
      MSSQL_SA_PASSWORD: "Pk12345678"
      ACCEPT_EULA: "Y"
   restart: always
   ports:
        - "1430:1433"    
   volumes:
      - cardbvolume:/var/opt/mssql/data

volumes:
  cardbvolume: